<?php

namespace Database\Seeders;

use App\Models\Absence;
use App\Models\Department;
use App\Models\User;
use Illuminate\Database\Seeder;

class UsersDummyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Don't hardcode IDs - let auto-increment handle them
        // This prevents duplicate key errors when seeder runs multiple times
        // external_id is auto-generated by HasExternalId trait
        Department::firstOrCreate(['name' => 'Nerds']);
        Department::firstOrCreate(['name' => 'Genius']);

        User::factory()->count(5)->create()->each(function ($u) {
            if (random_int(1, 4) == 3) {
                Absence::factory()->create([
                    'user_id' => $u->id,
                ]);
            }
        });

        $u = User::query()->latest()->first();
        Absence::factory()->create([
            'user_id' => $u->id,
            'start_at' => now()->subDays(2),
            'end_at' => now()->addDays(1),
        ]);

    }
}
