<?php

namespace Database\Factories;

/* @var Factory $factory */

use App\Models\Client;
use App\Models\Document;
use Illuminate\Database\Eloquent\Factory;

class DocumentFactory extends \Illuminate\Database\Eloquent\Factories\Factory
{
    protected $model = Document::class;

    public function definition()
    {
        return [
            'size'              => $this->faker->randomFloat(2, 0.1, 100),
            'path'              => '/storage/documents/' . $this->faker->uuid . '.pdf',
            'original_filename' => $this->faker->word . '.pdf',
            'mime'              => 'application/pdf',
            'integration_type'  => 'local',
            'source_type'       => Client::class,
            'source_id'         => Client::factory(),
            // external_id will be auto-generated by Document::boot() method
        ];
    }
}
