<?php

/** @var Factory $factory */

use App\Models\Document;
use Faker\Generator as Faker;
use Illuminate\Database\Eloquent\Factory;

$factory->define(Document::class, function (Faker $faker) {
    return [
        'name' => $faker->word,
        'size' => $faker->randomFloat(2, 0.1, 15),
        'path' => $faker->filePath(),
        'original_filename' => $faker->word . '.pdf',
        'mime' => 'application/pdf',
        'integration_id' => null,
        'integration_type' => null,
        // external_id will be auto-generated by Document::boot() method (see app/Models/Document.php)
    ];
});
