<?php

/** @var Factory $factory */

<<<<<<< HEAD
use App\Models\Client;
=======
>>>>>>> copilot/fix-document-view-access-issue
use App\Models\Document;
use Faker\Generator as Faker;
use Illuminate\Database\Eloquent\Factory;

$factory->define(Document::class, function (Faker $faker) {
    return [
<<<<<<< HEAD
        'external_id' => $faker->uuid,
        'size' => $faker->randomFloat(2, 0.1, 100),
        'path' => '/storage/documents/'.$faker->uuid.'.pdf',
        'original_filename' => $faker->word.'.pdf',
        'mime' => 'application/pdf',
        'integration_type' => 'local',
        'source_type' => Client::class,
        'source_id' => factory(Client::class),
=======
        'name' => $faker->word,
        'size' => $faker->randomFloat(2, 0.1, 15),
        'path' => $faker->filePath(),
        'original_filename' => $faker->word . '.pdf',
        'mime' => 'application/pdf',
        'integration_id' => null,
        'integration_type' => null,
        // external_id will be auto-generated by Document::boot() method (see app/Models/Document.php)
>>>>>>> copilot/fix-document-view-access-issue
    ];
});
