file_uploads = On
memory_limit = 512M
upload_max_filesize = 256M
post_max_size = 256M
max_execution_time = 600
default_charset = "UTF-8"

; OPCache settings
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 60

; Display errors in development
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
